---
  - name: Install httpd service
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: httpd_result
    until: httpd_result is success
    retries: 3
    delay: 5

  - name: Enable and start service httpd
    systemd:
      name: httpd
      enabled: yes
      state: started

  - name: Append vagrant user to apache group
    user:
      name: vagrant
      groups: apache
      append: yes
      state: present

  - name: Alter /var/www/html folder ownership
    file:
      path: /var/www/html
      owner: apache
      group: apache
      mode: u=rwx,g=rwx,o=r
      follow: yes # Previous to Ansible 2.5, this was no by default.

#  - debug:
#      var: httpd_result

#  - debug:
#      var: hostvars